package com.model.event;

public enum FootballMatchEventType {
    PASS_COMPLETE, INTERCEPTED, FOUL_COMMIT, OPPOSITION_FOUL, OFFSIDE, SHOT_ON_TARGET, SHOT_OFF_TARGET, SHOT, PASS, GOAL, SAVE, CORNER, NO_BOOKING, YELLOW, RED;
}

